Adds ruby 3.1.6 and 3.3.2
rwx-research/mint-leaves pull request #102
Opened 2024-06-03 13:29 UTC by TAGraves

2024-06-03 14:37 UTC, dan-manges approved these changes

2024-06-03 14:46 UTC, dan-manges requested changes
https://cloud.rwx.com/mint/rwx/runs/c1e6160c4a6745cebcecff87642048da

2024-06-03 14:47 UTC, dan-manges commented
```yaml
tasks:
  - key: ruby-3-1-6
    call: 25ab1454585dc3fee0ffc88aaaea5c4b0d352ba57137d53f3938805bf4b845ff
    with:
      ruby-version: 3.1.6

  - key: ruby-3-3-2
    call: 25ab1454585dc3fee0ffc88aaaea5c4b0d352ba57137d53f3938805bf4b845ff
    with:
      ruby-version: 3.3.2

  - key: ruby-3-1-6-test
    use: ruby-3-1-6
    run: ruby -v | grep '^ruby 3.1.6 '

  - key: ruby-3-3-2-test
    use: ruby-3-3-2
    run: ruby -v | grep '^ruby 3.3.2 '
```

2024-06-05 16:41 UTC, kylekthompson approved these changes

2024-06-05 16:45 UTC, merged